# Infra
kafka.bootstrap.servers=localhost:9092
kafka.transaction.timeout.ms=1000
schema.registry.url=http://localhost:8081

# Topics
telemetry.inbound.topic=someTopic
telemetry.outbound.topic=someOutboundTopic
# TODO: add DLQ

# ConsumerGroup
kafka.consumer.group.id=telemetry-flink-group

# Flink
flink.checkpoint.interval.ms=10000
flink.parallelism=1 
# TODO: increase parallelism after testing

# Backend
state.backend=rocksdb
state.ttl.minues=10

# Serialization
avro.use.generic=true